config/routes.rb
# frozen_string_literal: true

RedisWebManager::Engine.routes.draw do
  # Configuration
  get :configuration, to: 'configuration#index'

  # Keys
  get 'keys' => 'keys#index'
  get 'key' => 'keys#show', as: :show_key
  get 'key/edit' => 'keys#edit', as: :edit_key
  put 'keys' => 'keys#update', as: :update_key
  delete 'keys' => 'keys#destroy', as: :destroy_key

  # Clients
  get :clients, to: 'clients#index'

  # Actions
  delete :flushdb, to: 'actions#flushdb'
  delete :flushall, to: 'actions#flushall'

  # Root
  root 'dashboard#index'
end

app/controllers/redis_web_manager/actions_controller.rb
# frozen_string_literal: true

module RedisWebManager
  class ActionsController < ApplicationController
    # DELETE /flushdb
    def flushdb
      action.flushdb
      redirect_to root_url
    end

    # DELETE /flushall
    def flushall
      action.flushall
      redirect_to root_url
    end
  end
end

app/controllers/redis_web_manager/application_controller.rb
# frozen_string_literal: true

module RedisWebManager
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :authenticated?, if: :authenticate

    private

    def authenticated?
      instance_exec(&authenticate)
    end

    def authenticate
      RedisWebManager.authenticate
    end

    def info
      @info ||= RedisWebManager::Info.new
    end

    def connection
      @connection ||= RedisWebManager::Connection.new
    end

    def action
      @action ||= RedisWebManager::Action.new
    end

    def data
      @data ||= RedisWebManager::Data.new
    end
  end
end

app/controllers/redis_web_manager/clients_controller.rb
# frozen_string_literal: true

module RedisWebManager
  class ClientsController < ApplicationController
    # GET /client
    def index
      @status = info.status
      @url = connection.id
      @clients = info.clients.map(&:symbolize_keys)
    end
  end
end

app/controllers/redis_web_manager/configuration_controller.rb
# frozen_string_literal: true

module RedisWebManager
  class ConfigurationController < ApplicationController
    # GET /configuration
    def index
      @configurations = info.configuration
      @status = info.status
      @url = connection.id
    end
  end
end

app/controllers/redis_web_manager/dashboard_controller.rb
# frozen_string_literal: true

module RedisWebManager
  class DashboardController < ApplicationController
    # GET /dashboard
    def index
      @information = stats.map { |k, v| { name: k.to_s.humanize, value: v } }
      @status = info.status
      @url = connection.id
      @memory = keys_by_type(data.keys, :memory)
      @cpu = keys_by_type(data.keys, :cpu)
      @client = keys_by_type(data.keys, :client)
    end

    private

    def stats
      @stats ||= info.stats.symbolize_keys.slice(:redis_version,
                                                 :redis_mode,
                                                 :arch_bits,
                                                 :process_id,
                                                 :os,
                                                 :role,
                                                 :config_file,
                                                 :connected_clients,
                                                 :blocked_clients,
                                                 :uptime_in_days,
                                                 :used_memory_human)
    end

    def keys_by_type(keys, value)
      keys.map { |key| key.slice(:date, value) }.sort_by { |key| key[:date] }
    end
  end
end

app/controllers/redis_web_manager/keys_controller.rb
# frozen_string_literal: true

require 'multi_json'
require 'pagy'
require 'pagy/extras/array'
require 'pagy/extras/bootstrap'

module RedisWebManager
  class KeysController < ApplicationController
    include ::Pagy::Backend

    def index
      # Keys
      @keys = info.keys.map { |key, index| format_key(key, index) }.sort { |a, b| a[:key] <=> b[:key] }

      # Status & Url
      @status = info.status
      @url = connection.id

      # Pagination
      @pagy, @keys = pagy_array(@keys)
    end

    def show
      @key = format_key(params[:key], 0)
    end

    def edit
      @key = format_key(params[:key], 0)
    end

    def update
      old_key = params[:old_name].presence
      new_name = params[:new_name].presence
      redirect_to root_url if old_key.nil? || new_name.nil?
      action.rename(old_key, new_name)
      redirect_to keys_url
    end

    def destroy
      key = params[:key].presence
      redirect_to root_url if key.nil?
      action.del(key)
      redirect_to keys_url
    end

    private

    def item_type(e)
      begin
        ['json', MultiJson.decode(e)]
      rescue MultiJson::LoadError
        ['string', e]
      end
    end

    # Get values for Redis List type
    def get_list(key, opts = {})
      start = opts[:start] ? opts[:start].to_i : 0
      stop  = opts[:stop] ? opts[:stop].to_i : 99

      length = info.llen(key)
      values = info.lrange(key, start, stop).map.with_index do |e, i|
        type, value = item_type(e)
        { type: type, value: value, index: start + i }
      end

      { length: length, values: values }
    end

    # Get values for Redis Set type
    def get_set(key)
      values = info.smembers(key).map do |e|
        type, value = item_type(e)
        { type: type, value: value }
      end

      { values: values }
    end

    # Get values for Redis Zset type
    def get_zset(key)
      values = info.zrange(key, 0, -1, withscores: true).map do |e, score|
        type, value = item_type(e)
        { type: type, value: value, score: score }
      end

      { values: values }
    end

    # Get values for Redis Hash type
    def get_hash(key)
      value = Hash[info.hgetall(key).map do |k,v|
        type, value = item_type(v)
        [k, { type: type, value: value }]
      end]

      { value: value }
    end

    def get_value(key, opts = {})
      type = info.type(key)
      case type
      when 'string'
        { value: info.get(key) }
      when 'list'
        get_list(key, opts)
      when 'set'
        get_set(key)
      when 'zset'
        get_zset(key)
      when 'hash'
        get_hash(key)
      else
        { value: 'Not found' }
      end
    end

    def format_key(key, idx)
      {
        id: idx,
        key: key,
        expire: info.expire(key),
        value: get_value(key),
        type: info.type(key),
        memory: info.memory_usage(key)
      }
    end
  end
end

app/helpers/redis_web_manager/application_helper.rb
# frozen_string_literal: true

module RedisWebManager
  module ApplicationHelper
    require 'pagy'

    include ::Pagy::Frontend

    def status(value)
      if value
        content_tag(:kbd, 'ON', class: 'bg-success bounce')
      else
        content_tag(:kbd, 'OFF', class: 'bg-danger bounce')
      end
    end

    def url(value)
      content_tag(:kbd, value, class: 'bg-dark')
    end

    def expire(value)
      if value == -1
        'No expiration date'
      else
        distance_of_time_in_words(value)
      end
    end
  end
end

app/helpers/redis_web_manager/clients_helper.rb
# frozen_string_literal: true

module RedisWebManager
  module ClientsHelper
    def age(value)
      time_ago_in_words(Time.now - value.seconds).humanize
    end

    def flags(value)
      {
        A: 'Connection to be closed ASAP',
        b: 'The client is waiting in a blocking operation',
        c: 'Connection to be closed after writing entire reply',
        d: 'A watched keys has been modified - EXEC will fail',
        i: 'The client is waiting for a VM I/O (deprecated)',
        M: 'The client is a master',
        N: 'No specific flag set',
        O: 'The client is a client in MONITOR mode',
        P: 'The client is a Pub/Sub subscriber',
        r: 'The client is in readonly mode against a cluster node',
        S: 'The client is a replica node connection to this instance',
        u: 'The client is unblocked',
        U: 'The client is connected via a Unix domain socket',
        X: 'The client is in a MULTI/EXEC context'
      }[value.to_sym]
    end

    def events(value)
      {
        r: 'The client socket is readable',
        w: 'The client socket is writable'
      }[value.to_sym]
    end
  end
end

app/helpers/redis_web_manager/dashboard_helper.rb
# frozen_string_literal: true

module RedisWebManager
  module DashboardHelper
    def graph_canvas(data, id)
      if data.nil? || data.empty?
        # FIXME: Put the link of the doc where we explain how to call the perform method from data.rb.
        content_tag(:div,
                    'You don\'t have any RedisWebManager keys yet into your redis database.',
                    class: 'm-5 text-center')
      else
        content_tag(:canvas,
                    nil,
                    id: id,
                    width: 800,
                    height: 400,
                    data: { canvas: data.to_json })
      end
    end
  end
end

app/views/redis_web_manager/shared/_form.html.erb
<%= form_tag update_key_path, method: :put, class: "form-horizontal center" do %>
  <div class="form-group">
    <%= label_tag :key, "Name key:", class: "control-label" %>
    <%= text_field_tag :key, @key[:key], class: "form-control" %>
    <%= hidden_field_tag :old_key, @key[:key] %>
  </div>
  <%= submit_tag "Submit", class: "btn btn-default btn-primary" %>
<% end %>

app/views/redis_web_manager/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
  <div class="container">
    <%= link_to 'Redis Web Manager', root_path, title: 'Redis Web Manager', class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Redis Web Manager">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'Dashboard', root_path, title: 'Dashboard', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Configuration', configuration_path, title: 'Configuration', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Clients', clients_path, title: 'Clients', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Keys', keys_path, title: 'Keys', class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Flush ALL',
                      flushall_url,
                      title: 'Flush ALL',
                      method: :delete,
                      data: {
                          confirm: 'Are you sure you want to flush all DB ?'
                      },
                      class: 'btn btn-sm btn-danger nav-link text-white mr-xs-0 mr-md-2' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Flush DB',
                      flushdb_path,
                      title: 'Flush DB',
                      method: :delete,
                      data: {
                          confirm: 'Are you sure you want to flush DB ?'
                      },
                      class: 'btn btn-sm btn-danger nav-link text-white' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/redis_web_manager/shared/_status.html.erb
<div class="row my-4">
  <div class="col-12">
    <%= url(@url) %>
    <%= status(@status) %>
  </div>
</div>